In [1]:
import tensorflow as tf

In [3]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
tensor_one_d = tf.constant([2,0,-1])
print(tensor_one_d)

tf.Tensor([ 2  0 -1], shape=(3,), dtype=int32)


In [6]:
tensor_two_d = tf.constant([
    [2,0,-1],
    [3,4,4],
    [2,-5,6]]
)
print(tensor_two_d)

tf.Tensor(
[[ 2  0 -1]
 [ 3  4  4]
 [ 2 -5  6]], shape=(3, 3), dtype=int32)


In [10]:
tensor_three_d = tf.constant([
    [[2,5,-1],
     [3,5,8]],
     [[2,5,-1],
     [3,5,8]],
     [[2,5,-1],
     [3,5,8]],
     [[2,5,-1],
     [3,5,8]],
  ])
print(tensor_three_d)

tf.Tensor(
[[[ 2  5 -1]
  [ 3  5  8]]

 [[ 2  5 -1]
  [ 3  5  8]]

 [[ 2  5 -1]
  [ 3  5  8]]

 [[ 2  5 -1]
  [ 3  5  8]]], shape=(4, 2, 3), dtype=int32)


In [12]:
print(tensor_three_d.ndim)

3


In [13]:
tensor_one_d = tf.constant([2,0,-1], dtype = tf.float32)
print(tensor_one_d)

tf.Tensor([ 2.  0. -1.], shape=(3,), dtype=float32)


In [14]:
import numpy as np
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [15]:
tensor_array = tf.convert_to_tensor(np_array)
print(tensor_array)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [16]:
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns = 3,
    batch_shape = None,
    dtype = tf.dtypes.float32,
    name = None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
