In [1]:
import tensorflow as tf

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2,0,-1])
print(tensor_one_d)

tf.Tensor([ 2  0 -1], shape=(3,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [2,0,-1],
    [3,4,4],
    [2,-5,6]]
)
print(tensor_two_d)

tf.Tensor(
[[ 2  0 -1]
 [ 3  4  4]
 [ 2 -5  6]], shape=(3, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
    [[2,5,-1],
     [3,5,8]],
     [[2,5,-1],
     [3,5,8]],
     [[2,5,-1],
     [3,5,8]],
     [[2,5,-1],
     [3,5,8]],
  ])
print(tensor_three_d)

tf.Tensor(
[[[ 2  5 -1]
  [ 3  5  8]]

 [[ 2  5 -1]
  [ 3  5  8]]

 [[ 2  5 -1]
  [ 3  5  8]]

 [[ 2  5 -1]
  [ 3  5  8]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
print(tensor_three_d.ndim)

3


In [ ]:
tensor_one_d = tf.constant([2,0,-1], dtype = tf.float32)
print(tensor_one_d)

tf.Tensor([ 2.  0. -1.], shape=(3,), dtype=float32)


In [ ]:
import numpy as np
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [ ]:
tensor_array = tf.convert_to_tensor(np_array)
print(tensor_array)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [ ]:
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns = 3,
    batch_shape = None,
    dtype = tf.dtypes.float32,
    name = None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [2]:
fill_tensor = tf.fill(
    [2,3] , 5, name = None
)
print(fill_tensor)

tf.Tensor(
[[5 5 5]
 [5 5 5]], shape=(2, 3), dtype=int32)


In [6]:
t_size = tf.constant([[1,2,3], [3,4,5]])
print(tf.size(t_size))

tf.Tensor(6, shape=(), dtype=int32)


In [7]:
random_tensor = tf.random.normal(
    [3,2],
    mean = 100.0,
    stddev = 1.0,
    dtype = tf.dtypes.float32,
    seed = None,
    name = None
)

In [8]:
print(random_tensor)

tf.Tensor(
[[100.25331   99.73033 ]
 [100.85829   98.87001 ]
 [101.250626  99.054146]], shape=(3, 2), dtype=float32)


In [12]:
with tf.device('GPU:0'):
  tf_var = tf.Variable(0.2)

In [13]:
print(tf_var)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.2>


In [14]:
print(tf_var.device)

/job:localhost/replica:0/task:0/device:CPU:0
